telemetry-incoming:
  handler: services/telemetry/incoming.handler
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:BatchWriteItem
      Resource:
        - "Fn::GetAtt": [TelemetryTable, Arn]
  events:
    - iot:
        sql: "SELECT * FROM 'roborover/telemetry/#'"

telemetry-get:
  handler: services/telemetry/get.handler
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
      Resource:
        - "Fn::GetAtt": [TelemetryTable, Arn]
  events:
    - http:
        path: api/telemetry
        method: get
        cors: true