control-post:
  handler: services/control/post.handler
  iamRoleStatements:
    - Effect: 'Allow'     
      Action:
        - iot:DescribeEndpoint
      Resource: '*'
    - Effect: 'Allow'      
      Action:
        - iot:Publish
      Resource: 'arn:aws:iot:${self:provider.region}:#{AWS::AccountId}:topic/roborover/control/*'
  events:
    - http:
        path: api/control
        method: post
        cors: true